### ISSUE TITLE
[BUG] I cannot update a runcard

### ISSUE THREAD

**Issue by AlbertMitjans** [qilimanjaro-tech/qiboconnection#94]
Running the following code fails:
```python
from qiboconnection.api import API
from qiboconnection.connection import ConnectionConfiguration

import qililab as ql

config = ConnectionConfiguration(username="qat", api_key="meow")

api = API(configuration=config)

modified_runcard = api.get_runcard(runcard_name="galadriel")

platform = ql.build_platform(runcard="dummy/soprano_master_galadriel_main.yml")

modified_runcard.runcard = platform.to_dict()
api.update_runcard(runcard=modified_runcard)
```
Returns:
```console
[qibo-connection] 0.12.0|INFO|2023-10-04 16:39:22]: Storing personal qibo configuration...
[qililab] [0.20.4|WARNING|2023-10-04 16:39:23]: Cannot set `output_i=3` and `output_q=2` in hardware. The I/Q signals sent to sequencer 1 will be swapped to allow this setting.
[qililab] [0.20.4|WARNING|2023-10-04 16:39:23]: Cannot set `output_i=1` and `output_q=0` in hardware. The I/Q signals sent to sequencer 1 will be swapped to allow this setting.
[qililab] [0.20.4|WARNING|2023-10-04 16:39:23]: Cannot set `output_i=3` and `output_q=2` in hardware. The I/Q signals sent to sequencer 3 will be swapped to allow this setting.
[qibo-connection] 0.12.0|ERROR|2023-10-04 16:39:23]: {
  "title": "MethodNotAllowed",
  "status": 500,
  "detail": "405 Method Not Allowed: The method is not allowed for the requested URL. 500 Server Error:  for url: https://qilimanjaroqaas.ddns.net:8080/api/v1/runcards/2"
}
[qibo-connection] 0.12.0|ERROR|2023-10-04 16:39:23]: {"title":"MethodNotAllowed","status":500,"detail":"405 Method Not Allowed: The method is not allowed for the requested URL."}

Traceback (most recent call last):
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/errors.py", line 59, in custom_raise_for_status
    raise HTTPError(json.dumps(json_text, indent=2), response=response)
requests.exceptions.HTTPError: {
  "title": "MethodNotAllowed",
  "status": 500,
  "detail": "405 Method Not Allowed: The method is not allowed for the requested URL. 500 Server Error:  for url: https://qilimanjaroqaas.ddns.net:8080/api/v1/runcards/2"
}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/albertmitjans/Developer/qililab/dummy/update_runcard.py", line 15, in <module>
    api.update_runcard(runcard=modified_runcard)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/api.py", line 967, in update_runcard
    runcard_response = self._update_runcard_response(runcard=runcard)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/api.py", line 975, in _update_runcard_response
    response, status_code = self._connection.send_post_auth_remote_api_call(
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/connection.py", line 47, in decorated
    raise ex
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/connection.py", line 44, in decorated
    return func(self, *args, **kwargs)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/connection.py", line 294, in send_post_auth_remote_api_call
    return process_response(response)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/util.py", line 153, in process_response
    custom_raise_for_status(response)
  File "/Users/albertmitjans/Developer/qililab/.venv/lib/python3.10/site-packages/qiboconnection/errors.py", line 63, in custom_raise_for_status
    raise HTTPError(json_text_str, response=response) from ex
requests.exceptions.HTTPError: {"title":"MethodNotAllowed","status":500,"detail":"405 Method Not Allowed: The method is not allowed for the requested URL."}
```

**Comment by JavierSab** [comment]
https://github.com/qilimanjaro-tech/qiboconnection/pull/92 should fix this
